# pdf-generator.yml
name: 'pandoc-pdf'
description: 'Generate pdf files based on latex qm templates and markdown files.'

inputs:
  template-directory:  # id of input
    description: 'Directory containing the qm latex templates'
    required: true

  document-directory:  # id of input
    description: 'Directory containing the documents to convert'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  options: '-v ${{ inputs.template-directory }}:/data -v ${{ inputs.document-directory }}:/data/documents'
