# pdf-generator.yml
name: 'pandoc-pdf'
description: 'Generate pdf files based on latex qm templates and markdown files.'

inputs:
  template-volume:  # id of input
    description: 'Volume containing the qm latex templates'
    required: true

  document-volume:  # id of input
    description: 'Volume containing the documents to convert'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.template-volume }}:/data
    - ${{ inputs.document-volume }}:/data/documents
