name: Create and publish Docker image

on:
  push:
    release: ['main']

env:
  REGISTRY: docker.pkg.github.com
  IMAGE_NAME: steadysense/pandoc-pdf/pandoc-pdf

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: steadysensedev
          password: ${{ secrets.GH_PKG_REGISTRY_TOKEN }}

      - name: Publish image to github registry
        if: success()
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest --progress "plain" --rm=false .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

